### ISSUE TITLE
nettes command

### ISSUE THREAD

**Issue by fendi1989** [AttackTeamFamily/cobaltstrike-bof-toolset#1]
please any example of the command?

netuse (devicename) (sharename) (password) (/USER:username) (/DELETE) (/PERSIST).

can you put a example of the command, I tried but its not working I think.

**Comment by tionwayne2021** [comment]
redwarden ... do you receive outputs of your interaction with your beacon

i do not please i really need help

**Comment by tionwayne2021** [comment]
> Tionwayne what kind of help?

![unnamed](https://user-images.githubusercontent.com/86231696/136702658-08e29093-862e-44a7-b1ce-372a3ecdb2e7.png)

no response from beacon they connect but i cannot interact successfully please help 
email - tionwayne2021@gmail.com

**Comment by tionwayne2021** [comment]
> You are talking about netuse command??

redwarden not netuse

**Comment by tionwayne2021** [comment]
> Red Warden is working ok for me, i can interact with beacon. If you want i can teamviewer you so i can help

please check your mail
